services:
  # web:
  #   build: .
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./src:/code/src
  #   env_file:
  #     - src/.env
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: aistudio
      POSTGRES_PASSWORD: aistudio
      POSTGRES_DB: aistudio
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
