import { ArrowUpRight, Code2, PanelsTopLeft, Cloud, ArrowRight } from "lucide-react";
import { Link } from "react-router-dom";
import { Reveal } from "@/components/site/Reveal";
import { MethodExplorer } from "@/components/site/MethodExplorer";

const teams = [
  { name: "AI / Backend", icon: Code2, body: "Model integration, RAG, agents, evaluation, APIs, and the services behind your product." },
  { name: "Frontend / Mobile", icon: PanelsTopLeft, body: "Embedded AI experiences, product interfaces, and mobile applications shaped around the people using them." },
  { name: "DevOps / Infrastructure", icon: Cloud, body: "Deployment, CI/CD, observability, and the infrastructure a dependable production system needs." },
];

export function AboutPage() {
  return <main className="design-page about-page">
    <header className="design-hero about-hero"><Reveal className="about-hero-copy"><p className="studio-kicker">About Neuronetis</p><h1>Built by engineers.<br />Grounded in your business.</h1><p>We help software companies find where AI creates real value, then take responsibility for building the system.</p><Link className="studio-text-link" to="/pricing">Find your starting point <ArrowUpRight size={17} /></Link></Reveal><Reveal className="about-hero-image" delay={.15}><img src="/images/connected-systems.jpg" alt="Interlocking glass and metal sculptures representing connected engineering disciplines" width="1536" height="1024" fetchPriority="high" /></Reveal></header>
    <section className="design-section about-manifesto"><Reveal><p>Strategy matters when it leads to<br className="hidden sm:block" /> <span>a system that works.</span></p></Reveal><div className="manifesto-detail"><p>We work with your existing product, data, and engineering team. The right solution might improve what you already run, add a focused capability, or become a new AI-native system.</p><p>Our role is to understand the problem, choose the simplest architecture that solves it well, and make it practical for your team to operate.</p></div></section>
    <section className="design-section" aria-labelledby="method-title"><Reveal className="section-intro"><p className="studio-kicker">Our approach</p><h2 id="method-title">Clear decisions.<br />At every stage.</h2><p>Explore the path from the first question to a system you can measure and improve.</p></Reveal><MethodExplorer /></section>
    <section className="design-section team-section" aria-labelledby="team-title"><Reveal className="section-intro"><h2 id="team-title">Specialist depth.<br />One engineering team.</h2><p>Senior engineers across three disciplines, brought together around the scope of your project.</p></Reveal><div className="team-layout"><div className="team-image"><img src="/office-view-graded.jpg" alt="The Neuronetis workspace overlooking the city" loading="lazy" width="900" height="1100" /></div><div className="team-disciplines">{teams.map(team => <Reveal key={team.name}><team.icon size={26} strokeWidth={1.3} aria-hidden="true" /><div><h3>{team.name}</h3><p>{team.body}</p></div></Reveal>)}</div></div></section>
    <section className="design-section" aria-labelledby="principles-title"><Reveal className="section-intro"><h2 id="principles-title">A few things<br />we won’t compromise.</h2></Reveal><div className="principle-grid"><Reveal className="principle-card principle-iris"><span>Your system</span><h3>Ownership.<br />Without a catch.</h3><p>All code belongs to you. Documentation, deployment instructions, and operational guidance make the handover part of the work.</p><ArrowUpRight size={26} aria-hidden="true" /></Reveal><Reveal className="principle-card principle-dark" delay={.1}><span>Our judgment</span><h3>The right tool.<br />Even when it isn’t AI.</h3><p>We recommend conventional software or a better process when it solves the problem more simply. Technology follows the outcome.</p><ArrowRight size={26} aria-hidden="true" /></Reveal></div></section>
    <section className="design-section fit-section"><Reveal><h2>Built to extend<br />your team.</h2><p>Our strongest partnerships have a technical owner: a CTO, engineering lead, or founder who can collaborate throughout the work.</p></Reveal><div className="fit-list">{["B2B SaaS & software products", "AI-first startups", "Scale-ups with proprietary data", "Engineering & platform teams", "Agencies with AI projects"].map(item => <div key={item}>{item}<ArrowUpRight size={19} aria-hidden="true" /></div>)}</div></section>
  </main>;
}
